server:
  port: 7003
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka7003.com #地址
  client:
    fetch-registry: false #自己就是注册中心，职责是维护服务，不需要检索服务
    register-with-eureka: true #不将自己注册到
    service-url:
#      defaultzone: http:${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
